config/routes.rb
Rails.application.routes.draw do
  resources :posts  
  resources :profiles  
  root 'profiles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :profile, foreign_key: 'profile_id'
end

app/models/profile.rb
class Profile < ApplicationRecord

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all   
  end

  def show
    @profile = Profile.find(params[:id])   
  end

  def new
  end

  def create
  end

  def edit
    @profile = Profile.find(params[:id])   
  end

  def update
    @profile = Profile.find(params[:id])   
    if @profile.update_attributes(profile_params)   
      flash[:notice] = 'Profile updated!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to edit profile!'   
      render :edit   
    end   
  end

  def destroy
    @profile = Profile.find(params[:id])   
    if @profile.delete   
      flash[:notice] = 'Profile deleted!'   
      redirect_to root_path   
    else   
      flash[:error] = 'Failed to delete this profile!'   
      render :destroy   
    end   
  end

  def profile_params   
    params.require(:profile).permit(:name, :description, :email)   
  end   
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
      <%= render 'shared/sidebar' %>

    <!-- Page Content -->
    <div id="page-content-wrapper">
     <%= render 'shared/navbar' %>

      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>

  </div>
  <!-- /#wrapper -->

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/profiles/index.html.erb
<h1 class="mt-4">Profiles</h1>
<p>A list of available profiles</p>

<table class="table">   
      <thead>   
      <tr>   
        <th scope="col">Name</th>   
        <th scope="col">Description</th>   
        <th scope="col">Actions</th>   
      </tr>   
      </thead>   
      <tbody>   
      <% @profiles.each do |profile| %>   
          <tr>   
            <td><%= profile.name %></td>
            <td><%= truncate(profile.description, :length => 75) %></td>   
               <div>   
               <td>   
                <%= link_to 'Show', profile_path(profile) %>   
                <%= link_to 'Edit', edit_profile_path(profile) %>   
                <%= link_to 'Delete', profile_path(profile), method: :delete %>   
              </div>   
            </td>   
          </tr>   
      <% end %>   
      </tbody>   
    </table>   

app/views/profiles/show.html.erb
<h1 class="mt-4"><%= @profile.name %></h1>
<p><b>Description:</b> <%= @profile.description %></p>
<p><b>Email:</b> <%= @profile.email %></p>

<br>

<table class="table">   
      <thead>   
      <tr>   
        <th scope="col">Title</th>   
        <th scope="col">Description</th>   
        <th scope="col">Posted</th>   
        <th scope="col">Actions</th>   
      </tr>   
      </thead>   
      <tbody>   
      <% @profile.posts.order('posted_on DESC').each do |post| %>   
          <tr>   
            <td><%= post.title %></td>
            <td><%= post.description %></td> 
            <td><%= post.posted_on&.strftime("%-d %B %Y") %></td>     
               <div>   
               <td>   
                <%= link_to 'Show', post_path(post) %>   
                <%= link_to 'Edit', edit_post_path(post) %>   
                <%= link_to 'Delete', post_path(post), method: :delete %>   
              </div>   
            </td>   
          </tr>   
      <% end %>   
      </tbody>   
    </table>   

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>

app/views/shared/_sidebar.html.erb
<div class="bg-light border-right" id="sidebar-wrapper">
<div class="sidebar-heading">Start Bootstrap </div>
<div class="list-group list-group-flush">
  <a href="/" class="list-group-item list-group-item-action bg-light">Home</a>
</div>
</div>